services:
  db:
    image: pgvector/pgvector:pg16
    container_name: django_rag_db
    environment:
      POSTGRES_DB: django_rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d django_rag"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: